-- MySQL Script generated by MySQL Workbench
-- ven. 12 janv. 2018 11:45:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gazetteer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gazetteer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gazetteer`;

CREATE SCHEMA IF NOT EXISTS `gazetteer` DEFAULT CHARACTER SET utf8 ;
USE `gazetteer` ;

-- -----------------------------------------------------
-- Table `gazetteer`.`place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gazetteer`.`place` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`place` (
  `place_id` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `place_nom` TINYTEXT NOT NULL,
  `place_description` TEXT NULL,
  `place_longitude` FLOAT NOT NULL,
  `place_latitude` FLOAT NOT NULL,
  `place_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gazetteer`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gazetteer`.`user` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_nom` TINYTEXT NOT NULL,
  `user_login` VARCHAR(45) NOT NULL,
  `user_email` TINYTEXT NULL,
  `user_password` VARCHAR(64) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_login_UNIQUE` (`user_login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gazetteer`.`authorship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gazetteer`.`authorship` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`authorship` (
  `authorship_id` INT NOT NULL AUTO_INCREMENT,
  `authorship_user_id` INT NOT NULL,
  `authorship_place_id` INT NOT NULL,
  `authorship_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`authorship_id`),
  INDEX `fk_authorship_1_idx` (`authorship_place_id` ASC),
  INDEX `fk_authorship_2_idx` (`authorship_user_id` ASC),
  CONSTRAINT `fk_authorship_1`
    FOREIGN KEY (`authorship_place_id`)
    REFERENCES `gazetteer`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorship_2`
    FOREIGN KEY (`authorship_user_id`)
    REFERENCES `gazetteer`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gazetteer`.`variante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gazetteer`.`variante` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`variante` (
  `variante_id` INT NOT NULL AUTO_INCREMENT,
  `variante_nom` TINYTEXT NOT NULL,
  `variante_lang_code` VARCHAR(45) NOT NULL,
  `variante_place_id` INT NOT NULL,
  PRIMARY KEY (`variante_id`),
  INDEX `fk_variante_1_idx` (`variante_place_id` ASC),
  CONSTRAINT `fk_variante_1`
    FOREIGN KEY (`variante_place_id`)
    REFERENCES `gazetteer`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO gazetteer_user;
 DROP USER gazetteer_user;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'gazetteer_user' IDENTIFIED BY 'password';

GRANT ALL ON `gazetteer`.* TO 'gazetteer_user';
GRANT SELECT ON TABLE `gazetteer`.* TO 'gazetteer_user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `gazetteer`.* TO 'gazetteer_user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `gazetteer`.* TO 'gazetteer_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
